id: I2E118D9E
default_language: bo
source: ''
initial_creation_type: tmx
imported: 2022-12-14 17:59:36.712086+00:00
last_modified: 2022-12-14 17:59:36.712093+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-073-001
  eft-text-version: 1.2.2 2020
  title: Toh_340-The_Hundred_Deeds-v2
bases:
  64E0:
    source_metadata: null
    order: 1
    base_file: 64E0.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
